[tool.poetry]
name = "oh-yay"
version = "0.1.0"
description = "Citations"
authors = ["Joe Redmond"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
